imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    esi:             { enabled: true }
    #translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/java/compiler.jar
        yui_css:
            jar: /home/php/yuicompressor-2.4.6/build/yuicompressor-2.4.6.jar
        yui_js:
            jar: /home/php/yuicompressor-2.4.6/build/yuicompressor-2.4.6.jar
    assets:
        home_css:
            inputs:
                - bundles/nelmioslow/css/reset.css
                - bundles/nelmioslow/css/main.css
                - bundles/nelmioslow/css/print.css
            filters: 
                - ?yui_css
                - cssrewrite                

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

jns_xhprof:
    location_lib: %kernel.root_dir%/../../xhprof/xhprof_lib/config.php
    location_config: %kernel.root_dir%/../../xhprof/xhprof_lib/utils/xhprof_lib.php
    location_runs: %kernel.root_dir%/../../xhprof/xhprof_lib/utils/xhprof_runs.php
    location_web: http://localhost/xhprof/xhprof_html/
    enabled: true

